create_product:
  path: /create_product
  controller: App\Controller\ProductController::create
  
add_product:
  path: /addProduct/{slug}
  controller: App\Controller\CartController::addToCart

edit_product:
  path: /editProduct/{id}
  controller: App\Controller\ProductController::edit

edit_category:
  path: /editCategory/{slug}
  controller: App\Controller\CategoryController::edit

product_list:
    path: /{page}
    controller: App\Controller\ProductController::list
    requirements:
      page: '\d+'
    defaults:
      page: 1

product_show:
  path: /{slug}
  controller: App\Controller\ProductController::show
  requirements:
    slug: '[\S]+'

api_login_check:
  path: /api/login_check


